apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-storage-ssd
  namespace: gotosocial
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-ssd
  resources:
    requests:
      storage: 50Gi
