apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-ssd
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-ssd
  resources:
    requests:
      storage: 5Gi
