apiVersion: ENC[AES256_GCM,data:TCA=,iv:LeWLLvtXExPJkPs9Co9Okco1Q2kLE3sxwPagTT1lgAQ=,tag:BuZUl9jxx+uvH/w3l31zww==,type:str]
kind: ENC[AES256_GCM,data:J7qKPYpL,iv:hmogTHemRcI+voUNyj0f2S6GtLbC5cE1IWzWaE/V1a4=,tag:FnfvF4R5am3a9VKXdTmnQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QJIkYjGh58aOHSUNcdfp,iv:BRmg9s//6T/xaGsdWnyn8IMUfEXwW+JmhYCc1/vmX+0=,tag:Oh+dAVPU+U75HLJS+Mtyig==,type:str]
    namespace: ENC[AES256_GCM,data:buvC9/CgtOCcF4+P,iv:quZHw/YnAsDPS4895a16aMliziDSEjiWZVhKX3QykaM=,tag:qrekZHGtNhY1zzusht3NHQ==,type:str]
type: ENC[AES256_GCM,data:s/2Jgzsv,iv:U8K04wOElBGgsUoTVUJtaC3VETA8a8/Uygnpr64PFgw=,tag:RtCUm0dbD8qBWwRds6rf8g==,type:str]
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:y/vc27lZNcrBzJxAE3O2jQcmx+I=,iv:aMSRTHOL42xcfa/xjX1TaOh5RsxC96arAo1R+zD9Pt8=,tag:rLrYuYUqMit/Un9G3k9+JQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SqCmekE5cmoP/UuVtXB7R+RhyqsWLS+0SM6tUC+j602ihG6cmMcd9Q==,iv:CLTMeT3ifWBZbqDXMCcL4RA1sNhaoGSpuMxVzJnN4e0=,tag:DbWNWksD7VGAjuRaq+6gcg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleGFVbDRwSDNzbFZEbW12
            WUs4WVlEZHBoMHlYTzJBemthT2VydENuR0RFCkU2dXFpbjRhdlgwY3dGOTVsOEEv
            VFQrUjQ3anJRbDNrLzNmMkF1Unc1MFkKLS0tIHlyN3oxL1dROUxvSU9PV2hYT0xG
            UzBBdEY5UktxUGVjVGJlUjZmdzFnelUKfCY4T1d0bVB3teBQmji2JaFEVSck4XIC
            IVrJo6ar2ffkPcfMnFfEWjvgRSGUjXrHzUKIhDFOWDn1H/o/B+a8UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T19:47:46Z"
    mac: ENC[AES256_GCM,data:CjCPQ6KslOFExAXhSA/AFpS2S22DoTwa5o+9m5MDqtslyED+8EzowJHHwt9WvBiT9OCIZt039d7GNYdUyLYEVgYTZfSb9VBSX6ks1ZY3xYRunebM9xCThfM08x+K1ugPmj5z053vNMWnN5zpH9JfILAQPAY/ej8uxAJmAuVRTpQ=,iv:MA40M3e+JxMu25aVAbPVSQlym9rodFSYTO8Sm33rPZA=,tag:KNd5K/0YTyAkIcm36XCZWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
