apiVersion: ENC[AES256_GCM,data:xg4=,iv:tkpAt1KBtzJ/p5qj5lgj/C2WhEUoag64vOLF/uPrYuw=,tag:J6RvasOQ3Pmkhj73TcjyRw==,type:str]
kind: ENC[AES256_GCM,data:wejwanIw,iv:vqKFHjrY5/CvK6sU/lqBddYXdgg4moTkkkhFc17Fqjk=,tag:Mbi0dhWG7RAk47Q7h6Ol0g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LKzk6bfm6bEtzD35v5Nt/7sb0MTKWBs=,iv:NgHJ5hwntJnPjOdS5nMIIVRGvmRRPoov/oMgQMDxp2Y=,tag:uhmKjo89g8h8JIjiMq6srA==,type:str]
    namespace: ENC[AES256_GCM,data:utfuvDX8,iv:sAPD3TWn2NF6l6IUUDPwPP4fVmKYveLERfGEmLZ4avk=,tag:WDyHkbg4J15crc/scAvWHg==,type:str]
type: ENC[AES256_GCM,data:7n5J1yzp,iv:5iQxFkwEKvBRv4fpF8TOu8SIAH0S9TRg99MV6ur0MiQ=,tag:rKcLDKQ4lf/MJYMBRHOCSQ==,type:str]
stringData:
    config: ENC[AES256_GCM,data:YywNpIBkrLRPbLn9oGWszSAf++QQlfph2ruMYqkxzk8A34A25Gq2vDyrPqQJ29gQv8FTY2C/HLRvyDb9Z87OeNRUV2xP4A/gL9fDJtp9p19nry+dFtN+9hTPssXGhti+vscbLrwLxkM3csGNqyM89BKRO9hItuXMwg85+90QM8bJYrdpb0Fh5AFl4L2vFASJReigGpbewhaKToe3KZFpZpht7QrfiM9WjbS+TXgCAR3CcuEs6vsp7/QWJrSfrD6vsa405wwt2OkKkJAfHIVLb7gZsqw=,iv:d7h2VkDLWpJCuZN33506AZAPYXbMmZjFdzpkjQMR62E=,tag:Lp74CcGjKgWWYb9uQcIDPw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTUNVMG11SWFYUW8yQVFD
            dlAwK1VNVkM4cUVDa0Z2QzdoWFZ2bk9Na0FzClkxVFpNY2Z5SjhsRTg1NTlLTW1V
            V1htKzZXaFlXclhoVm53alE3NTF2SHMKLS0tIHlGV1pxUUY2VTl3czlrU20yd2RC
            RWJxeGY1MGgxVEd6dnBkTTVwQTQyMzgKVxITpPWgXBVkEteRExLE6l+JzKUro6lJ
            7i6nLzkd9IPdPvORPOH2SBgs6qdlts+db5ic9ez3dR6mS7c/YSZLFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:38:47Z"
    mac: ENC[AES256_GCM,data:6qG0M2wqG0SV+dCaEdZOc/cb5uJlQ5omNSzRyWdicfdyc2awQNiYXYD6KOfm2aYp3SjCC0f8b6mYejUUxJxPSgzv8br79Y+Ob5UShDPk2Mz9wbkg5NZQ6acDmx38z4rOJukxoln/1+6qfB5SDEPWqzgc4aRVRPkhOQRJXVNm8qY=,iv:/hm1uDzLtb2ENqM9I1hp+gA3NIa5xSUvdpWjuSgsAQU=,tag:TdMolLLnVyXHhdY6opdgSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
