apiVersion: ENC[AES256_GCM,data:7/g=,iv:0mw6UM6LdtBDQ1GCjLgc3zFr8QeVVnwZIhRzlppi2g0=,tag:BEJwpq479JAP8/exrPNHPw==,type:str]
kind: ENC[AES256_GCM,data:s0kLh7km,iv:rDCuvFDJIAS+kCoiJEDrcmL3ZYv2bPgNzqVX1laQgE0=,tag:LA6RNRZAMLixCQ5JEqjitQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:htB4GuNfCL2HKeSioPn4sgG8JFI=,iv:vn1H2fvWXloPzAXLfMpSgbK+FY/63fIeMw8yqah4U50=,tag:qECoR4qSWpya5uuxVcuuKQ==,type:str]
    namespace: ENC[AES256_GCM,data:SNo5wHr0,iv:jfEzNg42SJqYnEVyjO/xUTx6Rl/jt09fhI8kffuPCC8=,tag:jcHQ/GUJ40RMC7fxLMO0Xg==,type:str]
type: ENC[AES256_GCM,data:epZGLfMP,iv:YfIim1CBzpSpJSx9L6lc73JRP4wfwjLxp2Crk9k2A4w=,tag:YB/xsso8H5pknqxsYh6x7w==,type:str]
stringData:
    connection: ENC[AES256_GCM,data:e+X6QhDvflqrb+VYgmqGAEeYo+iHJL4g15Atf+GRZtknF9rMJnxxojzoMKEEYkccGcESTk4DCf+fHwJKP4Lu24VunOj7CjAsov2HbmoeT782WIjszV3z/jO7tzw9PyLK/y8ad7SNEPqi3Yoqr8g2B0mrmzJiqN4/i8SJXMCywBCyhmSZDEqrNDI8Rh0ZuATMGzbiVA1wMAMZaBwwYDgErCuKaFh2Z3Vc78dKW5Wrs2FLDrHLVepF37wxwIGQVFRudvA=,iv:6LQQ+cH15wu39ItBm4XhNmMAgfGnzlYdHZgt/Tvd1lk=,tag:13Hiamm1CVxw2gpWU63Zqw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTDZGcHNmNlNWZVRwTDJG
            VHBqTEZyaGNBR0FJSThUczI4UEdEZWRUSGhZCkhwdFBkVE1pbGdreU50RmZpQVcw
            USs5NFVWSEdLdE1oN0Q3QUdrZzNQckkKLS0tIHJzaVJJWldxR1pzRU91WUJNYk90
            TE8wNW1icjlKNXY1M3AreDlOb0VFSW8KSVedMcsNSv8uvXtnqGziqZh53GuCK3pk
            APnpSdKb/lQhNE5Ln9qyBVn3bHYlUFRc1YHWX6uk7/iI+AJDxb6DMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:38:47Z"
    mac: ENC[AES256_GCM,data:1kLPQL5ixdCmNhk5wkcGTk9UpcyOEX/rxUwfpCMFZ+RuAaHLpj6lUrV05U8E7OBDJsSO+4yY++/Yn7woa2SJ2dH5z2nWLoK0dy9YFxMRsdFha8S1Mic6IkYWmo5PAi/hSVrkjwFxAMqXIGbpQIvZ5TpBSsUPmP+K/D9eGMsR9lw=,iv:i/BZgUmhjJeO7Q5jJ+3ULEHC4BWpfoKC2VYMs7fPth0=,tag:YtJOcvnKAKCxW3aPQCIUMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
