apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitlab-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.enc.yaml
  - ./secret-valkey.enc.yaml
