apiVersion: ENC[AES256_GCM,data:Bck=,iv:TkMg65E6oe1Qfoe/D5MnirhC21z+UaVPyymaQYHSvs0=,tag:hzspKVOFqXqeX5MkOmeOOw==,type:str]
kind: ENC[AES256_GCM,data:aEgGgyyH,iv:1mhodUNE41+T9IvQLU8g1Oscrdw8hV1gvQ5B/tE0bL0=,tag:FeuGdz7ctCMSJ3R38FwQ0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lxhnQLYZzt0mNyc=,iv:/fbW+8pl9jIVKTp/n97V8NuRIPYWl6RYnyN/746fcAM=,tag:YzI369Lr9s9pX/VJGHyOyw==,type:str]
    namespace: ENC[AES256_GCM,data:0n4RD60s,iv:q1kqr/v1CUSoYHgzlTtffnQEsWt1HHpo43HYsN9ngVk=,tag:cEAGtWDub1SfgKH6gacVPw==,type:str]
type: ENC[AES256_GCM,data:Vi9MYsOv,iv:82xqckoGOt0DdDnW7mf8xoePLtz7bUngJh4lIZNK91E=,tag:7mokE9NFf+2YhZ36M2syNA==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QFN3cONLBo5OYck0lV0o4oH6CS8=,iv:RSqS1ypp7vnYLXYh50+kPLQv0KNivFA5ZdOaJWEuOFs=,tag:iGk7/qo8C2W52uAU3OeqVg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rDToWbHcAEjn4EhIwHp2RsCzYPW4mhSGFxkeEC28MqyqSbgFrpmRPA==,iv:f+iZOgYUfwqRJqARyCzdKd+wLWZ5wD+496EzREnly6A=,tag:4o4x9EqDgHLYW5Sd6N2QvQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0dsamtIclFMbStpei84
            YWhiQ2djbEpzNmhZM29VUE0zcElNM2xubmpJCkdUd25vZ1hPTFphVXJjRkJNR2N4
            MEcyY2pVM3p5RnU3dXVFb3FMOXZWdEEKLS0tIDBTM1NhM0gyU29qMzk2V1NPZXdC
            K2VvQzNIRUNjUFFJaEJhQzJFUHZFblEK6iiKXA8iZlIMaWAJ7txcCKKl7Qf1rxc9
            rkH/dpT8/I2bXvN8oJS8geRvjvl2msAu9mv8XoCnjzN0v6gCvp1UZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T17:14:46Z"
    mac: ENC[AES256_GCM,data:B0mP5jYgJ/3etyOkblYpFHwtYxCiXq3gcdUYDE2wQ215A14DJaeGEVRIaozPqcLtM6KChXqsb45tPnTGE26jGbYMzcpOkE938b/P4u8ry0pNgO8QZuP3976ZDpH7uBvLJ9BetoWjuPV+ElIRIWKNNKJSc8kPa2FY3AgAqHLZnZo=,iv:Aw76me5y8++9SAXSJHjAg6h+mzdZlm69t2Ex99u3qfk=,tag:pkhLekxbeK9JvGAdA+dToQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
