apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitlab-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.enc.yaml
  - ./secret-valkey.enc.yaml
  - ./secret-s3-connection.enc.yaml
  - ./secret-registry-storage.enc.yaml
  - ./secret-backup-storage.enc.yaml
  - ./secret-smtp.enc.yaml
  - ./secret-initial-root-password.enc.yaml
  - ./secret-runner-registration.enc.yaml
