apiVersion: ENC[AES256_GCM,data:tSI=,iv:pgZQ3gLVHieaA+ux9dVfrJbjLgF0wRGeYCsKKFGIlQk=,tag:5/cQV3jDgUzCWBH52rs4+Q==,type:str]
kind: ENC[AES256_GCM,data:mmei9XDR,iv:ufrjk5heZX2HQb0w1RE+bH6L2IRI2zgvulYF5FVo3Xg=,tag:TUITLIHbUg2Ry7TWhdBm2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YDfYVUegS64b7wxP/w==,iv:735SFWcb+joOmrzZP6yzOQL56LWH/36JtWVgODpwXB4=,tag:YoadlaqvwxQkSX6ug59zwQ==,type:str]
    namespace: ENC[AES256_GCM,data:wkBMODvr,iv:D5LDCaD11stBMXDfrSLbEcWCEkitM72PSt33AhQa1KY=,tag:dJzwEqlhhk7Pnfyptjpk0A==,type:str]
type: ENC[AES256_GCM,data:Z9Zdi8W8,iv:eg/bWo/YJS2BSzcYUu2H0zsgk+K0UPpDRUIXl7u9sZw=,tag:Xb44lODGhlI/AppUkUQROQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:KChfkDBmmD1of+YNeDqu8YZ7RGzukS8ubtZ7dfH/f6I=,iv:SVhi4FQyTtUTYw0oiEhkSlP8tapxHOuaCBMr/AQcUGo=,tag:te3xEmHhW/nubKUjsUZn/A==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNTM4d05XK0xTYXcrdnFB
            eTZ3TzVIeTdIenNzbjNucmxzNVc5NG5VcVJzCnJoRkQrTTBIWGJzWGFOOW1MRk9z
            ZXVPMU93L1p6WUN3SFF5Wng4QkJ5N3MKLS0tIHVmSTVDS0xlRm15ckVSWnVUbTd3
            Wmc5U0VocnU0a0kzRTJxZDJaWE1EaTgKtQuicyIQEr2Z42YE6mJkXH+E3Xt7IYXi
            AIWBa2FBtmiMkOBlFrVnnzxrRxR7mwy3cM4a/uEUmGYQXeM6vtbEuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T18:08:07Z"
    mac: ENC[AES256_GCM,data:g+qhFR1qOYJ997w4DidIA30npnWNbOM5lkvk6pMDAmbCRodtc3pLgKkJ6VhLAPZoFGZOF2ItpvQN5s69V7BC69i22dNRVoeqnDXQmIiK6SimxDkYmxPeoNTVhFe2TJSFLNaXq8dx29l/1Bqt4fr4AbY82imyEbLIjUI6uGuooRM=,iv:bhxodC4RQGzjSGavRT6Ln4Ds2OHv9x24O3F93HdHJBE=,tag:x+0ystQO14k8bl4/DwnvkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
