apiVersion: ENC[AES256_GCM,data:1SU=,iv:GQ94oIPKbAPKUrvx6UOGMXbpfNE39T/716JOOa6B1kU=,tag:czuEAIUL5CHmcS+yfg2Znw==,type:str]
kind: ENC[AES256_GCM,data:oQR4HETw,iv:peDWOCSfoYPz1p1IEeIGf3PS11qj6XNOeDuj+Ap/Iq0=,tag:5ygjlKtDYAwVt36xsSCJKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CU9JpJFs5o5G2p0qO4FxAPlDzMxwACXQ9VKCwA==,iv:aGMCUucwOOmBOXCWYWThWYLGKPWBnySye9yH4xeV1V4=,tag:OxCGuUW1UM+dFyLT5Egv9w==,type:str]
    namespace: ENC[AES256_GCM,data:La+ji9fL,iv:34BU2mWZlbRFU9zWDenanLhp33PxwIRfuqP0DeckRcg=,tag:pMTjaA6/YiPoowk0P6pP6Q==,type:str]
type: ENC[AES256_GCM,data:/xwV3j70,iv:TvycVc59TSQLP6o9VZ+aryD1VDSr8qtaQJrGiO7pc1o=,tag:Rty3dgFNhyayhS88aHkfdw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:gzxSjQGx7cqC+xUPI7XFmvaGIOlTbIWB,iv:ENsb98qnbugq7vFitJRA6j47WN3cMvck2eGeYHunu0Y=,tag:e+gpKv+DvtIkar0XmrP5Uw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRnNaRUF5OWViYUFEMzd2
            NUxwZDM4MnBqUEtycmZPdlIrTzUxTjRmamlzClpkdHNxSTdpUGtXa0hJUWVXc1JV
            VzJKVk53UDVtQnIvUHg2WC9EU2gyMWMKLS0tIGhrQUNCTkpIZ0NJVWFOMUpDcDEw
            ZjE3OStPNjRQTlVkMngvcUUyaks0eGcKHjXa00oXj77OMRpPkKZePKPufIvBKIu1
            Vk/w38Qjz+7HW4lZ4md4DbVG9R8UQekADckrJREo2uV48XWjjx4BCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:38:47Z"
    mac: ENC[AES256_GCM,data:99pyGECggbSAfG2I4oPzGQ4pEBOIGdxgUrggDidouZA6lhx3ZuGO6+RhoYMaUZ3+2CD+TFaweJ3+yx2J80xsZgT/l02G4I5wDZSP0Z/0envo/+fc8j0qD6wlb4WtX0S6Mu4uCaRBpjuHjzQAVU2rt/mhDmVsSVC6oPQEeHnSRl8=,iv:JtvYueVgOlOZmSDMTRNYs3JhmF4qOAWp1YDaONN4SD4=,tag:FWsRIemK0n9y6OdEVxa7uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
