apiVersion: ENC[AES256_GCM,data:UrI=,iv:IimCGz7/bu36fbiCV/0ir0WHsRRJOYGYBYJEAuFwLoU=,tag:rbn19Oti3gVInO0ohPb0LQ==,type:str]
kind: ENC[AES256_GCM,data:z85FMbIn,iv:HQh7FfBd2OBFmfIgWTWo3jaXazkPeS2hQl6rESt3Bbc=,tag:PvT98S7lPygkdcEIjN62YQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:exdr5XH5PmKvVu9u4RQJ7lWZ8SlE,iv:x6F6KWXZD+2qj2ZGD6rvBnvtPM6Jk4feIlPEFlW2NkU=,tag:VTGeNUAV+LLi86GGq1LLoA==,type:str]
    namespace: ENC[AES256_GCM,data:2lI0kdCe,iv:10t2mW14h8wZewvu1gw7SRm4he8DUO0QKlfrZmZmeLg=,tag:tDTAWGEK3UTqVRg6k3JF/Q==,type:str]
type: ENC[AES256_GCM,data:6E3LCi/F,iv:UbmnBsQvniwc5fG1ahPPhCBNxM58lz+m08gRz8YcAAI=,tag:TqvoJ8DQY7ZF1Z+rbt1nIw==,type:str]
stringData:
    config: ENC[AES256_GCM,data:ykXYf4nRTTA1ApkwNepfsVoE3mSxI4W8q5IeNNbG1sBeTzXnfmcKzwlq/L6DOPJqQm3//qQACPCA9ozueMUUkg7nR7o+T7+a1W0fpEweD4Vfn3cFL1+ct/2CsJF5scnHS78swxN4ac0yt2who4FMbAPrhNhEdQp0sklngb8aDB1y+CjAScN+9uq0rPEsYxrDXHB/FHUXXitCbUEEtd113l3GoHfXRiiUQaPAqg+hhRoXJ3cu+2AqeBG0fRpN0Rma6+n1S0c=,iv:aUpvLBM+phtTlGMkJisZx903I6nqNp1BKmn4wJPR/9s=,tag:Ep+9ts5qWQiVzFLuw7qB5Q==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MnB6TFNlMjZBaXJiN3hU
            d0tSS0c4UCtiYWFvRHlERXJRMkg2SjVIT2xrCmliMW5iQ3o3cVN2a21pTlZOUGxq
            ajcyaGpDNjkxRFJoZEdKN2prNXFMcjgKLS0tIE1aUUFFTkFDajBXc0c4UE9YaXFJ
            SFhEblJYKzZzNEF5bVBnQWl1THllU0UK2qOlftUHreeYuJ55jmsWreNx2tHoN6rW
            4ECgJiqqMFN5Dynji315DUaB9+IIxUGx+M5bvluW7+wZSXtfddcQQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:38:47Z"
    mac: ENC[AES256_GCM,data:Oy7lhYQmEX8ePlD6ZSVtbT8qXUN4YsnH9NQnCHS7tdFG2SAWvyDwBoTG36lCTOQqDJ9DukFJ//rmv/FF7JAPaKbxEk6hGvGuOfkwo7b8O3kh6D8jKsdeHAPmaQgvFGlBiKoQLl8SVmllr6Ci716R5ZqsN8+ZRsV9JIt75yYYuZU=,iv:iRQEK5+fITTRLzi3ETPi2J9nBpNlUeJq+mmiSPLzjpo=,tag:54DHM+tSd99Wl82AInYD3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
