apiVersion: ENC[AES256_GCM,data:iqg=,iv:kltQQ4wzXiErI80U5A/BwcZLlG8xq3TToqfZqJSA/2I=,tag:WS2jf7j+mZ/e+83qmvIFIQ==,type:str]
kind: ENC[AES256_GCM,data:nZYv3i9X,iv:b1osEloLeD92+JjGeB/QfM1FQkAqWhu/cENaPUNYVag=,tag:DfBd9BLNP4FX6NhLodPlTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Pgw8gAWu8UIF358=,iv:paUsPKfwg8dzr9PD0fnQndOsB7g4RbLslXR2unSo0gw=,tag:sPdNXpRNbiLGl1aC4cybKg==,type:str]
    namespace: ENC[AES256_GCM,data:1E+aUATZ,iv:sEJ4L0a4420YtIoUeRU4nAI1qKoK9WhHKegf06ClTWI=,tag:VZFa1DGRBgQrd2D9vNYaBg==,type:str]
type: ENC[AES256_GCM,data:wrYSgOM3,iv:yK2mk7x8eQyU9JHoJJ9Aqq4p7oJ7kU2kc8V0Y+pI1Bw=,tag:tAeX5CHalD0pCijMoccPNA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:kKl0mDbrMIG9d9fvD+UFg0wVVPEijKBilVbIGU5cPL+riBYi,iv:zlfenJMFihTpj9yzzWHFIuFQLRrMfX1G6BRrX7VCCj8=,tag:dW3XTT67oReaM8jf5SjG3g==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOGFsUk9zTW5XRTBoVGM5
            MHBHbmVRQkhNNXoxSUswWmNEOEZRNEJLSUVnCittSWRrTmVMREpnbWdlczZiTnk4
            eTNpanEyTUJzeUpQOUF0VTV0R2xHZmsKLS0tIEJsV1pOckp5UlBwdzVnOGduRGJs
            cXVwREZhYzVra3doNk9sZEdWQlptNGMK1NubIIuuNyVwpjImdrN0+/yIG8XeTZ+N
            HC8K+/MTmkyM1DeJic45SK4SkP74FqQAYr1xczzqAsx0/Eg4Onh1/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:38:47Z"
    mac: ENC[AES256_GCM,data:+vb7Hi9c9p0ZR083WG5e3lEdwjVjRApsTVkLm563Vmb7+Qt0c8Umc6JyQRODTgGUd+PHMBvmNlW4chxT4SqVyyg6GzxYp2RfDwNfTm3d+4KpmF/p/RpgECXA75CMbz5pRvBNMR8CY/BbZh79jTjzo7xVWmbMXQgj4av3khHkqLQ=,iv:Bn5YQWVUC7nMRlTr6/9k+60NYY29TrZa3gH1ipBiDjM=,tag:jYAUdCNxzUBB8Vw0B1c3eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
