apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asf-config-ssd
  namespace: asf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-ssd
  resources:
    requests:
      storage: 1Gi
