apiVersion: ENC[AES256_GCM,data:FWE=,iv:AhYSaTsUqFdXVKESY+i7jweuHXw979mP6/S8pp43imw=,tag:2yGbqetHD54JRhpJVV+dNg==,type:str]
kind: ENC[AES256_GCM,data:Q39+dyb2,iv:3bOysF2LLSpUrauTWbAJNvsFc+dk4K69EINS35AihSo=,tag:R5cUdXAiboE7r18oJoiRPQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:93A4wCK3LxxQTLKF,iv:UDwGdcS3gqJrbRhHanU3No6ZXy5Fa1AyAECJyu10A90=,tag:ZymUwIXQlQcksgEVohZMaw==,type:str]
    namespace: ENC[AES256_GCM,data:2aICHg==,iv:sT9fxRyicaN+ekKe3GDjOabyXVmDf59KNLEWHBjwhTQ=,tag:LRoLHagu/tlkqMJYfT36Yw==,type:str]
type: ENC[AES256_GCM,data:xXYZL3O7,iv:hhMO1ngkdt744kgEHSU8ZNsJF+uYv40vqtDRyxh4Zdk=,tag:OqTztTn7zdRjnIPI0yTBwg==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:x8Yslap133g8vL7mLRHPDeBW5IWEAUkJ/dADC4HooJW++p0fFv7QA7lJDamDvqdvOHdc3p9ZWGba4VhsGbMaIICQhMNYTtwe,iv:4nLYYXBbhJxxvlZnKMvJDlyHFGAvg7ycY2X/+qCANDA=,tag:dzzEC0h4JDe9GjllSIKEnQ==,type:str]
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:Bq86n+9wEfZQn9AsmYGRTGM10UDz65g/rpW+zw7RjmOCCbIFEsJi,iv:Xm6q1KL2bPHnRQmUGY9qiSfVhM5KKSj2sK9n3Ps9p1E=,tag:puCqn0jePBbIauVvtLcu+g==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UCtPM3hLRkFNN1F6OTFv
            NXRWQ29tYzh6WU14aWlhUDViK01KNEh6QjBRCnJCNkhoSHZoVmJMc0F1UjNQdGJQ
            TU1ya1ZmbkJLelc0NXJzdEo4bkJMUDQKLS0tIHc5K21rb2NwT2ZONWtSbDQrQjFU
            eEZFcGRsZUkzTTJmczFmWW9HN3k3ZzQKvW5tWBqtdTH5oGtT3pGQTRHUk7c4iwIO
            Kh+rCEc9SLAYyvYkJCy5ybWZm3M7jSVL6FWeA0GXd0lUne4YsMFl/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T18:09:09Z"
    mac: ENC[AES256_GCM,data:/zBRpEl0gb0pYIdu41S6jCs0FdmXPu4aXziYNLm0bWueSgi/khT5Uek1lH5KUOL5vd0d39v5HQ7Zj+Poy4a1b9PULKJGu0ovk/jD33/dLzZyFhn34nKBQjQbBxzxQNJQp7mK2iZGU+1ZuBYHlxnn4CRosVfhy058HI5HEIn0eh0=,iv:m3OjSGnqzGLFJVdyFXXCskEPD5YNIENyZ6SdTJQTz3M=,tag:+fnmrei9WJiTrcreyXtVWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
