apiVersion: ENC[AES256_GCM,data:PtU=,iv:LmuRettg/gkDpo3n6YW3hxHfjUQbEoshXwz0nF5yfOg=,tag:K2rwO3yPVWj9eFAe0dxQJg==,type:str]
kind: ENC[AES256_GCM,data:Hb2WwYA4,iv:MNOMe2FWJOQpJJ3sFPjDYMbLrru+ZdwXJxcwOJQh5VQ=,tag:jzJwFpLicV+xhr4yvq4MdA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x2CMcyzmWbd2Uj2TSFR4,iv:1etjbV+/g/i6Q+TzoWvQ6OhuAhJ5BOexf3v0XqAMd9o=,tag:XHH0oBXntdnLTcGeaxq1pw==,type:str]
    namespace: ENC[AES256_GCM,data:VYvI5r4VqvI=,iv:JlxNjlWWy4SNxZ2lZFw0BK4AWRGuil0x5iZO04eT50w=,tag:sVbR2W8hAz7QeocchvhhPw==,type:str]
type: ENC[AES256_GCM,data:GzeLQMOG,iv:XBR6UErPK2x1ZjZgCTkC5vwctuZYTncKzYURTRsWMak=,tag:f5RsbcA3c8s8gV1qi17TkQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:kzBHbw==,iv:LvpzbCBMhgZOScMxicedVeLN9ZKLgnhPNRhPzVLXBUI=,tag:g948LJ1/j2OV78vBHqdTWQ==,type:str]
    password: ENC[AES256_GCM,data:n7a8DzHfw41YE5B3qIM6Ti8U,iv:LoBx8E/OnA8YyaAeB3F82BKcx1GQvuyh6th7Rcs98+k=,tag:Ous4RMZofqbRzDBD9xaQ1w==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzKzdsNFBYVERiQ3FBRGpP
            WEhQY2xoU003WXFWdzhsOWdWR1pqUjR0NVdvCjBhYUpsSWdLa2hMbCtGZ3o1cWVI
            WWRISkR3WlowbjlFZnNXSGlqMlFzb3MKLS0tIGQwbjNWbmNVejVBc0Q4UXZpbUFs
            UnZBQzRVNnpFT0s0b1JxcnpPbmZWRkEKQAg2d2W7FsQN5Slb5ialvdeXMP8CgtMM
            K3HTJYZsgZxlzi1BgW5yjv5i9sx97LUV/pY9C9BXv7M975JpB7Q/NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:12:17Z"
    mac: ENC[AES256_GCM,data:Uc/YpGOlHjsoe5QiKUJpXHHFYsy0IbWbIRtE3dry2YBjG5xnrOsxIOj0zf/lka5pkyCLIWfz7p6g8c367NDwatw+ha+SFRo+N+QaJdXFNjvbHLgP6+otY6ldmugoaaaGntUduAQaGUQCfPv5uEa93fs8JDMCoitcnmA845cqCgk=,iv:pK6/yZ3UTHhgRd73OgI4v3xzOXvLVBMP8DBlPcjOWc8=,tag:bbT5vZsIqy3Tqdt6pwx91g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
