apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: openproject-pg-store
  namespace: openproject
spec:
  configuration:
    destinationPath: s3://cnpg-wal/
    endpointURL: https://nbg1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: cnpg-s3-wal
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3-wal
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 14d
