apiVersion: ENC[AES256_GCM,data:vWg=,iv:OJmVb5fMpSyQTlEhfSHs2Eq3GvAEppg+sp9NWX5wEIo=,tag:wHtCKVVqPVD1AVPGD+dodQ==,type:str]
kind: ENC[AES256_GCM,data:L8BzyUTA,iv:MT3miMYmZxRTGAaxWwDk/3bWzzPtrLFVL+Aqpfenh3E=,tag:PqtMn1LgMAHSbawY6QKkMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XyD8uuofTLROLZk=,iv:1As6zt3v7RqMH8TZHmjiRTFf+3iFoNSy8X4ctWwhZ5c=,tag:vhprZjaz1IuDf6lxczlH+A==,type:str]
    namespace: ENC[AES256_GCM,data:lkKea1UH5u0JLmc=,iv:FQ4sIcwIN4EETPevljuLTmMDJARdILYnak8Gqv8MtyM=,tag:Pi0AHhbmF28QJ/lYP40tfg==,type:str]
type: ENC[AES256_GCM,data:hhGeVte9,iv:+b6q7j1Qx4KRwMJOjBu4juBi7UZOaaFsTogBmz8ZI28=,tag:hbgjux/aEDUV8v4ZURRusA==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:IQiQ1I5R3MigL6lzsiSCxe0pzuo=,iv:NQo+1igVTwHXCL8bhgmOw/z9dhBXDfMzQhjAb9iC1rE=,tag:Sj62GU7Qle5G55t3GU/Feg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:9GBtJOT8iE5DfL2TIEi+3vm9ooSn6uKhJZ/k4ga+tdiINAcDYp1B7A==,iv:86R+w7FelSah294g6vFZ5g6SaoRP9BP6mx2lLYyK5NA=,tag:mlaDS89ienaMPcKjC5queg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkQyaTY0bDZEalNiS2pF
            Q3Z6Z0kxRzJOQ2s1c0pYSHpLMy82Q3ZWZEE4CnQ4SVA1ZEJrUzBtUis4SkZPZGpq
            YUNlUWVMa0VtTjl0QUJwZXM3OHBRcmsKLS0tIGozZWJneDJVbmVKa1NOYW9KUVND
            ak9KemliYmVaUVFFdGQ4dks0YjVoRDgKwLKhw7fMKqvoYQORVw+u4wdu/zMQqBbI
            acuINqbwUwDkzC6rx02kMtIsIGckpGUijdf05kJQ+/HGIuu+LEjViw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T15:26:17Z"
    mac: ENC[AES256_GCM,data:5lvTnW34pRkmYk+WboPn8GqFdR9XqFr0P/vBgPPDDxfJQ+Oa679kohMGLwNrI1Ns1Bcv0Tm1kkVLjRmebHvg55/5UGsIwj0qN2sbAVO+EtwtfDwY47q5lUcFy1WisCjDyX+NRN9jnCEyhqY2gJ/4J22u2ZIJMPhEbPU/NqbKVlA=,iv:0vwe0K09Js3VIiVibCBtJyYqjn9yzs+xN/dKk5K1tHY=,tag:snNpu0oydKO9nLX+9vOLWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
