apiVersion: ENC[AES256_GCM,data:V/4=,iv:zuigz/HliF4LJYqZSAQMP5qRqsNOB8MKorKNu6zW8N8=,tag:yz6XH/5iSmom+6MOH0Oisg==,type:str]
kind: ENC[AES256_GCM,data:vH8BuBmb,iv:U8hkzNUsfijKU67tTuJ3/mysdA/rvQZVBBo3ZxboE2k=,tag:jN6wY/uBxfbqOm6UWeyCrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FO3BiEA6weHT4bYFLbscEQ==,iv:ihXuS3FPzINlU8P1+D8JVySt9g5sgIvgwAzoyOZAdwE=,tag:dzdR5V0iFhN1YkBdXNfMXw==,type:str]
    namespace: ENC[AES256_GCM,data:oWKYuVsuo3zYUEo=,iv:aG3Di55tK+JQA2Hps7FqAktxvT10EDkb8kFo/dTbBqg=,tag:Oy4+7wSDdVk9ip4dtmSLog==,type:str]
type: ENC[AES256_GCM,data:D6Ntm49B,iv:UKkxv06Y4maS7HzzbNBIVLYejtZKYr8h4TRD2iA5iJU=,tag:v+00OVIKiE4u9Xn1HTVewg==,type:str]
stringData:
    OPENPROJECT_SMTP__PASSWORD: ENC[AES256_GCM,data:LrFvBwqVTs7DojvV+xGHAjaQKw3pJOBlFPMetU3tT6sY/L5d,iv:b+j42D/vADUsnXVN7jIrx4rkwGUIZueb9uRNFjJ+CX8=,tag:PW3vQ7IqPSLmVh4POR32dg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbHdwOE4rM1EwQVJZU1Rl
            SWhRdVIzaS9PNnU5MEg0cGpJbW1UMFlLQjNzCi80a1lLeU1OSjFwc2htSXhtN09X
            YldYc0Q0S1FhNEh1U2NWZ3BPY0l6bWcKLS0tIE5Lb1RBOXFrWSt2NVRGdWxRd0Vi
            bTBwOEcvLytkcG5iRWxZcFpoWFFOaDgKyOuXo8g1gQM32wJJNqfCSmWWk1lUab1k
            lh25VJPwcf38p1vHSJSaQX412WSYddAP2NEgZwgdbKkjX+5pw6VBuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:06:59Z"
    mac: ENC[AES256_GCM,data:OejE2KjCyt10ygMBhzGEaWPeZalXqtO2Bfzrg3dS5WCtfXuLdgaz6PrvPD+UbBywaz1k4/YNkNBMmyd+/laxcLUxTadL6o2gBxrc0j9U5QoqC5wIGAWGS3VG9K+njnQiF3DMyIIbfy8ihC/xkJWbJB5tBbuoiY+4ikZzjOUqBko=,iv:EIQ9/IH8Os+NmmdAh+EUkez5leQTbyDdpSipVd4lwCU=,tag:85Gv1NA62vDe6Q7VcE9ggw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
