apiVersion: ENC[AES256_GCM,data:hR4=,iv:VX02uLlDbeTml5SWc0NN9nr2VLDu3JBGUc/oUn+0oHc=,tag:kw+MWW57spJ2qyUvxbimhQ==,type:str]
kind: ENC[AES256_GCM,data:XjoI8uiY,iv:Mt1+VAdFHfhaP+fmzc0p6pd4lPXSx/MExIB6rRcyKiw=,tag:qbmeOtQTUIJnzx7db9OTjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LW1+nZKV3oKDAuJ6Dc3J+pNtHMp7HccOEa4=,iv:c+VDQNOt9giDeDdU0qcZMbFpTDXCvB0c6CqIEmaq2dU=,tag:3FWoJ1p/q997jxJDGGVsQw==,type:str]
    namespace: ENC[AES256_GCM,data:EWzhc2F4qGKRvMo=,iv:4HgY827x4UUq3HbNvNNzOluVC3POoasqgKe+oy0d5vQ=,tag:iVFOrRfLbebiFTEjLBck6g==,type:str]
type: ENC[AES256_GCM,data:Rn3K8pKx,iv:xbg5ZufypmtqcwP9o9e6hyXmCaXW2AmQFRWJc2aDb0Q=,tag:iyK1qIgdvo8kBXkC+2wMLg==,type:str]
stringData:
    OPENPROJECT_FOG_CREDENTIALS_AWS__ACCESS__KEY__ID: ENC[AES256_GCM,data:RIUdSFPmElHeVH5SUNpiriqpL8g=,iv:brnATQETBL/Zb7bKL+OZAmZQcPnY+tkVQbzQqWfHAZU=,tag:OqpV1yb94MSjQ8vGCfVRdQ==,type:str]
    OPENPROJECT_FOG_CREDENTIALS_AWS__SECRET__ACCESS__KEY: ENC[AES256_GCM,data:ihWhKpvRTu6MUs2d7iM79DhtdoVHmfk1ZVmF1uN44XW/soA/d+0seA==,iv:TgmrwgpBuYbP6ivw+p28ZG6JWJ7qnUGnVzv9zNWN+nw=,tag:+cPKOCZKsPlJsn1Ua4IEKA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTEovSHFyZDJjanI5VWht
            SkZHd1gxTzZNRlNwd2xaTndHVktCaHBBb3lBCkJSOUhQc1Z2NUllTCtPL3htaGN2
            Vm1yWVVsN1ZOZlljMDA2V2ljUXU5c2sKLS0tIFkxZXhVdmhnUXhHRUMwNmJROWhi
            WTlyYk1BOVg1NzB6TWdKVHc2SVd3eHcKm4QZJ6Oyvg7TpPUhcoGdSHhOJX4t2Dws
            VgWfmTuiM5J46ekY5+cWL3XcyqZjYeNK5xLWjqoU11vlsPNfcC4pJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:06:59Z"
    mac: ENC[AES256_GCM,data:rYbbLyRXzhGFoE403vfndC80XrII8mSXd0o1zeOBVSarWJqhzhd+t8zo0uiZojTyt8DIlWfjgUi1LivYqbJy28OMtFpzXZujrijfRF+KsfEZ7AUq+sG8pcPp0ycFJwFsuhTODZiF4FijxTCG2X8EhORjJityryLZt472KSsHYoM=,iv:nYOeziWJHo4C2SdFQGFHQMjy8zK2hBBToL9ozUZp9IQ=,tag:T6RCYGCNdw/MnWcyfwhpow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
