apiVersion: ENC[AES256_GCM,data:vKQ=,iv:aMInIzodKscWLxQvTW5oDMXvbLfZZHY4JpfpOUM1hf8=,tag:yZxgYLnM9mRygens2NypDQ==,type:str]
kind: ENC[AES256_GCM,data:yNOoVVwa,iv:8geBd+IwzRQ1nArfLuVub9gVE5d7DL7fCQqMIl/lxb0=,tag:Kg2f+GJCDqJCSaT9yegzAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EIvaUKmKPhlmVjaDTw+p,iv:iHm0SPVNRl9uA8bMNk4MiiU0V9PuulSlFim6A8GrFC4=,tag:5CHKZDdKOoTBguJ9zMZ1GA==,type:str]
    namespace: ENC[AES256_GCM,data:Jw+/00gThzabRGE=,iv:jcBlPN76CDuabzfGwhcDqhXTY5RcqWIRDB4aMxig79k=,tag:6ro3UmZmwNWR144EB5whDg==,type:str]
type: ENC[AES256_GCM,data:/Y9u4Jlp,iv:YfZIiekyu7QX/dPRRedkGLpNrHztygfTolI8FAc0SX0=,tag:1rWROWjzbKB02h9iNnMyqw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:I6BSoFwfQ8yIPuC2RTvUeKYDwIQad1lElg==,iv:XAjrhJft22idAO7sNbSPeXMnwjdW8XIvEt9AtY8Otd4=,tag:iWlEElpV8O4FqtNDolFDXg==,type:str]
    secret-key-base: ENC[AES256_GCM,data:zd74oC5zYxbd0HkAmBUotxVGAk8XXNBLddJjbq7C2Jwvk6mVpttVygJi4ruvynLmB1+nI6MIOd3e6LVYBvcaEDjlE5fgHPGrIEG47zMlcdQS3/VwqKvBKHiyHSOO8+4yPQreelgLMgK0XDqXpHhUNkOvQJH2LIVxzJAVlgSWtd0=,iv:13nzIwz0ut6dvE1Hlo92DpjUooLNfAKWDhtg1A8RBK4=,tag:hEd+Sm/1gZHuVImw900HtQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVGJvMDdBclhuNjdlUnVF
            eTlTV3ZPU2p0aTZ5NmVYbDVwTXY3cW1TZ25ZCjJTRVRWWjgrb1pkOVYzUWdrNW9Y
            VUQ0OGVRV0QraGhycnhRa0dhS3NDK0UKLS0tIE9XUVQ3RmFIWmtUMWtiWW9sRFdq
            c1ZhczUwY1BQaWJHdXVoVjREY214VVUKMUzDajqrdhm8AiUTJRxodj2cv7YPh5ZW
            rqdJ7e/vF+4PCDAal66UgdIrOpELG6TX7IaLgk2k0xxzgJq/G0pg/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:45:34Z"
    mac: ENC[AES256_GCM,data:AxXqt57VboZEBI35PrmXsZc/xac8aUW4hlWxTb8WUp8BZD9MApapWg6p8p57b7Q9/Zj6nC4L466IhfaZla09XW3WEqHh53icE/kvy6AOD43ImEBY02Zrah915roYvLsNkw6XdAnfsUJWMldpjojameQBAbbdhmcntMrHuQGfHTQ=,iv:DAVAjV9dohM1hYUdPGoZ3E8HYvfC5Enrxiw0RXNK9nk=,tag:1L+F7Vvjwq2ojvxHSSDt/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
