apiVersion: ENC[AES256_GCM,data:iJM=,iv:cQ9WwUIOmclEHSOacckF07IdyK7ZlaBuAqH4JefZeGM=,tag:Z0h/OkXnhXYo+0wO0CkoWg==,type:str]
kind: ENC[AES256_GCM,data:oChLShma,iv:M2ooMOgM2KVB9I7hRuWR5TDdGkVZqbCH6ZuYSSw7Hds=,tag:RODb45nKgWC2cR0IiE5OWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PKbd2ZsDvBKsmss9ReUI,iv:JmnDc/FQTYOi3nBIO2Yfxu5LE2cFVCGTMWqUMTYCcW4=,tag:oLMaEbdXmcfKCXjJx0Bajg==,type:str]
    namespace: ENC[AES256_GCM,data:Zfuzr+Yu3T3kQng=,iv:3kQgYHPOoyxUamXQTIqKLvZV1ZM3z2kjK66x4qmxRWg=,tag:H/1jee0Q+gszDjZ/L3pVZg==,type:str]
type: ENC[AES256_GCM,data:DwCpjNor,iv:31176UqYK9j1TD6bTS1crIu9QUbUYikxUtJi/Bjj/K0=,tag:cSgeUCe8KuUfNTTn5uC1xg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:jtNKcquPV/MXT3o79NRywAJhof8Il4e1PpgLWhPN,iv:bCutBN9HZuCX3fiN9hjgVVDdIryyBBI2q6OA7PbVfmg=,tag:KkuAQfk/K4m9XOKJK1Yu6A==,type:str]
    secret-key-base: ENC[AES256_GCM,data:7ktnAmk+UOf5GW+tPHYqIQQascLFV9YzaJPqLurVCi91Mwp1g/yozzwaegKySSEqzuGyoLmqdBcny8oC1YKPruS8evBumg89O4979RJ8gyu4PyyCA5x6zfTg/xRiZ1qBFKxKbniq1lfB6qTahzyHFG/5HNOhSerNh7IUhSReKRI=,iv:eO/4YQMz1j0Nit8I85MQtgSItnlpE7ghkwEs5lCwb6Y=,tag:TXzIhDHGdqMnQxc+dNUenw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVHBzMU10QzNnNVVGQW5M
            anNPTFBsd0lnY0h0aUNvcTJ0WEZYZ3MwMkNjCjJCZ243b0NaZFN0L1dqMWxwNGFh
            akRRLzRJSmxCUkg0dEVkMlB3SzE3Q0kKLS0tIERFVkRRY0p4OWIrSHV3Q0JxSjFM
            a1lBU24xTS9XRVVWVndnNGVTWTZpQXcKrjYizIELLke8E8ui+8Adz5KoLurKIGxX
            kdUG7QleTTVIsoFWiPrm8EwmmkjQnH2R4LoiS3/cyQ6ArIe0g4pqyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:06:59Z"
    mac: ENC[AES256_GCM,data:BQum4ciUqL0dof1Nd/ZfkcjPvLisZ+oqaa3vtk05Fqj4Hpm4MeE8wl1QW5rTiWYDXNk3OZ/grexdq+CMbOvy4AQrIuKiyldksrS+cXRSeCzT1Qof1HU+uVQafjBYnWD7InHhCHJpA4ngZ5hDHJt5f+0PZB5yGgH+Km8kmJb1ApE=,iv:wqXG+Nl3S/H00gyqvQE6JYIQWFFfkn+wi42x6DEUDVI=,tag:B3ovErSpjH+kN0eK/d1n4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
