apiVersion: ENC[AES256_GCM,data:A0g=,iv:TgVoVD6XKY2hzFRYgOMXcQximgcJHHFJPbspGsvLJf4=,tag:fT1Q6ZliDybTzIIyqm0Aew==,type:str]
kind: ENC[AES256_GCM,data:LtsrrokF,iv:3kULWTPlPE/LIFIdIW/giya23zak45zvEuvwUnm5bU4=,tag:wx7atI/5SRZ/e/0RpG4h8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1X723sp3LQOiUs8=,iv:fueA9AY0X113GZ0ElJJXra31xqFAe24kL/BqwVPaXBU=,tag:pDfHxaajmOSbT5+7DM79wQ==,type:str]
    namespace: ENC[AES256_GCM,data:jILAabgE,iv:QN0r/TiYD/PkONUaqdgNaQu9O2YL/z1q6ZHiuy+0S7g=,tag:pjJb9rIaZ6Mt/SMA09B4aQ==,type:str]
type: ENC[AES256_GCM,data:kpvQnXC0,iv:3a8GNb0RFr4RQEVNuQ5GHmrban67DW5m4I6w/qFeDCE=,tag:OUwEW01eKbWHvgjQjucNBw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vrfbvTY0PA4YD7uuGHvcX8oFQo4wsBFl,iv:LboYSxpsm3GGa7zA6JfHAJTfxWr8oKIJ7HDqL/nUkn8=,tag:USH0NGjCZMvHkVmbxrH7jw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:0TlvF0SAr2W7uiH6N0I4sS14eENNlP+lbbpu/Q==,iv:C9Rx7ilnQQtryTc6C9z+AU0qG23IWId3UzsHcbTerBw=,tag:ao2U7/JJdkDQbjRgCaf6WA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQml3QXdoTmpGamZsZmxF
            bks2a0pVR0l1c0dTY2RVQzZrNnBUSHhBQVdJCkZGVTQ3Q1UyMXRZMTVabnRKMGZ1
            L2kwZ1E4djY1d2ZuTUorL1FMK05IR1EKLS0tIHllK05yVTJ6My9udXpwRVNwRC96
            Z3RzWGR5UExMN0tqV2s0K1EyWmNVNnMKdppiMAmgC4EVa97A0lvZf4XFvlHeu6OL
            ej4asr0e2Eh0sDfLAmL+QzU28X9VRqlCxL0h+IEb2+RrTS3JPioEtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T21:30:19Z"
    mac: ENC[AES256_GCM,data:Q2HzfLSveGSQw+7hOklG3YtAyvr9udCZFFxGiV9H7djyUBG0/q1CQnIfgWcFUZdsNGuLfs3v3a9pofvH0OLc9q4/4lXXBqErYGuEA7FEmWAE2soq3UnJSrt5W2Mw38svq+hoHHJMabwmJMaVJISVe1DkD8eBBfhtbQ1IyHJYrYM=,iv:jVgGO5N0UJ3iawJnnCticN3NAsf2YTtIhbjBgq/KYTk=,tag:S+2+2BJStE+tRsGROtgzKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
