apiVersion: ENC[AES256_GCM,data:5Ck=,iv:jkwY5qOzSrp+UCbj6O1AIaqShDfb/4O6KGIOwBg51Cc=,tag:KKCjI/wFgaGSjZbcxdVx/g==,type:str]
kind: ENC[AES256_GCM,data:yLCWJTks,iv:zFNRmuouMLvwHksptM4TBFzUplsul47DvZyceHj4dKc=,tag:DU8MNHcUE24hui6/GEjLww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wO/3IzEEc/I4llM=,iv:KBgDgMTNtasF1FgAGRJ9ycSJLO7YkYCzwBBiQ+o4w2Q=,tag:krgiZItdlEjwX0F/9i1CCg==,type:str]
    namespace: ENC[AES256_GCM,data:AVkGrfOo,iv:0Mo+G6JC1sNE929aXk7baqkvS2PPW0WG5fI1afMBHVc=,tag:x5UikOpI/IhjU4APv3LwpA==,type:str]
type: ENC[AES256_GCM,data:MpNQ64qq,iv:TbLgsak5Jgofb/yrwKLYPnqQFjB8qDqM5kIqdSDIK9g=,tag:wbpve0jonTOaBV/nIaofCA==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:KuUwM8dGZzVwqC7hApKcINHrve4=,iv:kpnD9AtkjXQumRGd0fVRN/50X0m0wnAJsxKDeCv0DIc=,tag:Jt2ERIi8F3mDhwablgSn6Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ohsCEGTcLvkfks6H9B3usCdRQGhJDl/LVrKpSW6KPCcMfAZAwp4sOg==,iv:ZADAzLkjQzpnuc2S68HHXMB6QErKeqB9afCwirnWoGw=,tag:9ocRJCCbtFmsa8zIi/6oLA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYWs1aFFLMERzempickhR
            dFY1WkVWRjJMUFNkRERSRjhWTG1Mc25oMjJjCitUSWE3dTY1cG1PRWVOQkFNWFJQ
            d203OVdrT3VVWkg2akNsWmwzZ3AwTDAKLS0tIC9rT2JoeldUS1kzN0h4YUM4eDlU
            bDVxcTZ5bmxrT09iWWV1TWI5aFQrLzAKdzA+aUWzpM5oP3AAScw5r70kr4+r6lSA
            7KdNrAhTgMSSNy3kVYA7SmF+r5/A2ODDRSnmXPREGU0GpiKLJ2EUqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T08:09:11Z"
    mac: ENC[AES256_GCM,data:P7eHfugS/RZsnd/t5aLroDOqgwlvFHs/c7t+STFJj028EJsP3i7drjfGgJYT3lVBiHLOLLTR4QBVSC0bzUOon6AmqJR5V7v/n3QpoaGM1DrHVfE0Q5fTW4R/Lml6OlFNKF1wOVoErx4nwaEKxBX8tX+Zq85x7uM9qEzwjMGdJ3o=,iv:Xshuj/1ZN5zQbPzw5sTMSDQiLIleTKwAe9QeO3xXoPw=,tag:xCkGeh+x31uxkQYxFYJ+TQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
