apiVersion: ENC[AES256_GCM,data:KWE=,iv:089nwZxUkG4QNGM+ayYkAeFU85rML/yMIRlH1YJey/I=,tag:3Q1Di7yNrIcVGXx6TTPkQw==,type:str]
kind: ENC[AES256_GCM,data:00Tc/Sga,iv:zBHRYmYLomU4TSIEPb8U9soWyzSMe4tk0i7wQNKILOw=,tag:0u+CBkqVH6+nwbWRxwNjvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eQ9cjot13Www9g==,iv:IUMU83nyVcNizxJ1Q0Q1twCwiq5OAPXc3wiQmMkyApo=,tag:VqJW8gBBVSPaPUdNbdYrpQ==,type:str]
    namespace: ENC[AES256_GCM,data:6JIzjLGX,iv:VZfnCjQD87U/UzJE76X5WsMX1lyGTyNxzS3HG3Z8fp8=,tag:QTooK3fOt7KtT0oAMyThVg==,type:str]
type: ENC[AES256_GCM,data:aihD8V5q,iv:K+JmMbV27YYaLoJMrNrl95fRWttn8mC1d07kPR7zJBQ=,tag:Frg40HO6aEJax6ke4TFFHg==,type:str]
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:OH3NpoqHji/UKpqIjLDdfRjX1DTT+xwFX7kh1jGSEWQW9ypx,iv:ZkvAxhkqAXJNy6zJ1KexsBhBE8s6RCl00hWcWwGs6W4=,tag:B7gKe/pH0FXmShkk7U/meA==,type:str]
    BOOTSTRAP_ADMIN: ENC[AES256_GCM,data:RWSHdTwvJ0ozDz3dwxQ0tw==,iv:Ak6saCuyXvAYOgIPXbPE44X2NOcr2DnarmbtyVXUHEs=,tag:0pN7P4WvSjTfpvCb/OohbQ==,type:str]
    BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:j6OVmhC3/GSwYpVjSX9w,iv:7YD8zQz7a7nNa1Q4Bb2WNda3SOmVms/su0vAY2i+6YA=,tag:26ktFttJbKQlmzNpIz+MbA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bmNwVDA5YXhDdHVGWlFH
            Q1VOaHM1WGlVNVMxU0R3MzVNLzl6enFCUDN3CkJsT2hGenpHckZ1bStYeDZicDNn
            WEFyQStqa0xTeGlJK0g1OEpwY1NGR2cKLS0tIG1uMlFLbGg0akh4dW92eU1ncERm
            TThUODJBVER0VDBhNVB6MEtnSzQwZmMKsh7skJ02uPhlVoC7i18g6ZqHA1nO5Qn5
            jNKyfrWk2ytSYVLABwZqz5wyHhJvc0xdI4kR/zQLC+1cGsb1GspWRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T08:32:08Z"
    mac: ENC[AES256_GCM,data:LKPQKrccKz+lH0fOAlN72Yr3sXHfgIu/SU84/MevMEyJ0V+nXv2NcR2MZBbD6Lp1PdyHrrrudzwNK+nqtecY5SVVdt5NNGTuhZXoyOyAa3/B4apwDCem6Xlyzq7JiG6Q0bgi4KSqVWu9dTkxPM8Z9L/jUtGZsx2cp4I0K4JI9mI=,iv:CBJq3p6xCsS6bJ5vATdaH1JuJGtOmRdpo1ZO2fSTl7w=,tag:odmerAqMxmd4wqQyenwY+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
