apiVersion: ENC[AES256_GCM,data:IvU=,iv:bwAy9Vl9dWZpEo4zMr82vbHDfg2RX1NnNtvmjo0W/7s=,tag:5f92R8Xi9XPh9JskXZgbYw==,type:str]
kind: ENC[AES256_GCM,data:KxpWKIRs,iv:UeSY/xooy0lPpso3v6PwLTb5zA+2je7sPKWGQQL/ZVk=,tag:jVidNSCWjULfrwRtpTvNuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WEKl0nnfCqlkfQ==,iv:flX0DB9E2Qiht4zaiHuRqfKp3gu9t6pxVBueZ2MpTEU=,tag:g7Bl+jWJaf0MH0RM9h8LVA==,type:str]
    namespace: ENC[AES256_GCM,data:6hWU+/k5,iv:UwAOg4b5oblkTSsywck92JxuPQHapkww2InWC38mfPY=,tag:KHlR54wgiE6m8UFJtIcFPw==,type:str]
type: ENC[AES256_GCM,data:FtrP+f+D,iv:jsSaeueJQTiJsYGp1KT6VayK2TW8uHKcSjZgi8RWsjE=,tag:8ECLRpuCrJ+cEr+Isw7pTg==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:OrIU8pcXQhuCN6f4fNBumL1jLZHfMAo=,iv:wlAxBzcVa0nKgHbdH6FEAyWaj5KouO68sDlAJmnrEkk=,tag:ua3yvYD/PARXW4OyMrJOCg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:hql+jvQjzLCnWXeS86oo6nEcLwFVMOv+PQ==,iv:8x2roN1idMzwsIJe+MpRwKo25c2+brf+XBpgWrzbIyI=,tag:V9yALpbDtMFxbw5ibBOZ2g==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeUJUd0xKeGdmNlZQdG40
            bEgwQ0RSZGVUUlZadEhPWVlVRmZjbmVRNW1BCmRNczhTakJFdkxyRUhyQ2RaZXFH
            UGhTRU9wMEszMG94czFLMUZUZzN5ancKLS0tIGN0dzM5bDErTFYrcTc2STNDOTd3
            SEdielVTWUtaNUFKQzRIeHNMcndOT1UKNq/E0WjEUYKUR3e6xiL+9cfqKfO4vra/
            OQ97pfSuPIiSlC2YjM3zxWW6GtcFllug17cx4knMh3Ye6f235ZPUgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T21:30:19Z"
    mac: ENC[AES256_GCM,data:R2UQQCvuCEEWO91alvQvAt0tvyGaFRSdbqTN0hFdi+m23kqLe5T13C6BtNbXoMzBqCRiZi/MkyXqYILb7I59mNIa1tKn2kAm0hJ9CSHqp1ABaWcV4CJiWYHxbEMQRD02t3c/gwHzFYEMD+jfL2IDoJL4LmkPtm4M1hLvPEItuaQ=,iv:c4huWvWstyEcuhoefdV2HuxFvHE/moz6HUovXcn9e2k=,tag:nHpZe9Yz0ywFu6lW0lDWjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
