apiVersion: ENC[AES256_GCM,data:gLg=,iv:M94MefmixXdWZmZohu/bCW4a+ZhEWOu8sdmt+boUev4=,tag:EPR0KnLwaMgVqKz4icYGeQ==,type:str]
kind: ENC[AES256_GCM,data:7og2MF1a,iv:npUz/YAWV/Kz4xDFIDikT+lMLSM6JHBrO/0Q7ZyqwlU=,tag:cd7uqjxZqTpLerGaunuVKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l/IBnff88y7RAmw=,iv:OyK2nE4y9sJdbb3ZduiDtLeQaMe/2J9vxtqk8NDzzeY=,tag:JrEPMK8KoaxOzAqZy3dEBw==,type:str]
    namespace: ENC[AES256_GCM,data:PmSoXAN2dUdT,iv:ur7E+WOQWjT+He1jhtxsFQAo2lTeM7MHItQuqtIgTSg=,tag:ddmCwzPGf2DLJWYDcawoRQ==,type:str]
type: ENC[AES256_GCM,data:CNoxaeLH,iv:Phkf7tspZHgyBH5xC8YHzoafkMz5/S7eX9oTgWlHCzs=,tag:w/xuXe/ARLaEE3K5DTdSJQ==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zXQx3GxgAcYAxC8Fjp+kGRTc7w0=,iv:qNOF1Y7ae/E+BCbhGN7p6fHvY/yWR+xxl6dxctgaSo0=,tag:ldEyyjwbhSPTcc6OJA8idA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:xPwCDCyjLRvHKrg+2IS7bDYzi6Y2+BwHeSv4LbUubwZVkkB5v9sztA==,iv:e/yQIJpF8uEuDW13hO/2p5GdIJSskPko3a4rUrjJGtI=,tag:Xm+yM7233L5u9oG/mzZoMw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCajMvMFZ4Zmc5bUlZNi9V
            QzdHUm9nOVBXbjJYRkMwUFNwYkdEVWo1VFZvClBhdzZ4bStKQjFTOWdKK2pHM1dX
            dGFheFErdGJEUTNxb0F2eHRQYzR0aE0KLS0tIExpUFdsdGtzUjRHVFlPNjNlcDlq
            RnNyQldrODB6cnkzejFPb1ZxQVhUMmcKEfphn9qyqsQAgA7soCPDt4iBt+m/YuyD
            +CQ+Af5bkBT3z+f/TxmoKpDp1dXnz50P7yCiLFK0E89tFlIl7K0kZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T12:01:57Z"
    mac: ENC[AES256_GCM,data:1yOZOx4B9R+bnCqmJiLsP7PzZiuPIIEZFCRjCVjb3obPL6yySCNJcVBCIpJOaC08XCaubqVWSgESvZ3Jy5d+ApYCOxeranhROoePak8s62zBcqfu+od5T4AZk8v4vtmUzkUV1TInT1PKv7YHAqQffCa1NYPjmvkXsqA9dNsCfB0=,iv:NWXqVrO4GwDj6HIlDqz9YZMIQpJinj24eKo6/aey0rY=,tag:HLj2brnUZFK++sZxxU5Zyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
