apiVersion: ENC[AES256_GCM,data:Yd8=,iv:tHaj00SUyf+vxB8yxhmOonuOeuTtZId71z02Wid2bw4=,tag:UknFRNXtj4ske7m/6rPoBQ==,type:str]
kind: ENC[AES256_GCM,data:EkckArzJ,iv:GkrJysXLlVjxbMUCalZ6hkZqYbScVqHPZusYCxNTixg=,tag:P9EE6dEJLwGFFkZS3UiSPQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UMRy8FLn8LAaVcRD,iv:sjQenb2y7bEpSZsSIoNfvnl3QPT2r3xtE8t9k1FH254=,tag:DAwzKmPgPDY7wm43Zs7jYA==,type:str]
    namespace: ENC[AES256_GCM,data:QD1m9tbpe8vDPw==,iv:hpWuCz9bngyI38OUiWQYRic/IWKTXgyWu2Y1HSlD+BY=,tag:M+/AiS5CuQqaIwqcVEXEuw==,type:str]
type: ENC[AES256_GCM,data:pI3KHubI,iv:h7i5QKBxmKKwuIZ4WIg3euZ4Xzwt6eVqaIJDqnDEG7s=,tag:ICb1XqCBcsAYLuWVlTd6FQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:YZ9ZtVg6RTJPZQofD13L+MXrOY9ulWPI65/ftT4ml66QtfQUnZhPa1jYS8UEZMlKQvZ96mwJskoLjRcwPGGe+4o/rigHOa0uNhnnPGrTaqBj9HbiH2mvGMbXTyXxc0CYjoOrwHeZ7vwsuHnF3hTPv7bUKRW2V+fNrUOMJotcr+zxroASFmtbkkqvbkqLGwrudvk8ihnsA2Af6KHfsCIOZ1FAM7rsttefGcAzPXdQSrSMWq2DQq55jq5bXIZaiDHi4XcwJFqY4ggIcK/jO81aQr/+tPXs8Ldn7DGf1LvwGxRU3h+gzg7bJ4+4eQ/BcyKBV062vaqUhSH735atP9JiAUknieEa4hmNA0usDADqUQG1mfI6+UC5+pY6LJ67NYAT7vHwITXwmTW4wm0R9+glsV7qVSwguYzrc0aw/kivq9q3ZV2GpCT23Qcx+HBv49x/B/rP9t5uBCwr6jjHw7+MplanZroVu/9Gpx616V2FrdGNKr5nV58FCVJPQ7FE1+ZYVhMuCACvrELfAvyAooin5nEcgglBXp48A7kcy32J9WBQkPomJHZsJwRkct9Aq4OuijYug9okCD4nEQ==,iv:ZQmnuhHDNp2Twuqnllfp+qNqny+jpzN/pKXxnAY0v5E=,tag:tyIwBKKsY3kxYrYc0BASfQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGejRaajBvbnRLUHYzNnY0
            VHg1NlR4ZGtnRy8wQ3FXWUtZVkh5M2Urd1FrClNQZE0xWGI4OG5zRnhIUlg0ekpN
            VlNIcTQzVWpEdTJsNnNsREh0WFFiVnMKLS0tIFEwcmxvUmlCSGxpMWlTR3ZHTnlS
            VC8rMWNRTGdvd0NicDdTZjhjcjN0dHMKyOMDJ/bEnZnZcNyR1z5XVNLDmbJCxqWH
            jF/5o7VJKLM3Il/Waw7/8FcPAfnn05NfgkdV9syvUr5Jw9jqhxRbSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T16:33:17Z"
    mac: ENC[AES256_GCM,data:Ui+iT3Ji5x0V9q3PGZybThbL164vWOkoaMdvmalgH2cSqla9o7EvF1B9NOGw1QdZMinCftLWC1gcINkgmvJEDf7Cy1tBYHlq4jkOi2utA2dsi8cjTjP2yf7VOFO6C1R9HnQ5Y7zYAld5vXlqZGG39SPoomzuNt4Me/5tcfFnNwE=,iv:52HCBjRKbdlbHSPfd3NY4AQq0Mewbl56UIoCfmZ7cSw=,tag:7BQsz8c1oF1Ec+t8aa9y1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
