apiVersion: v1
kind: Service
metadata:
  name: dirigera-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: dirigera-exporter
    app.kubernetes.io/instance: dirigera-exporter
spec:
  selector:
    app.kubernetes.io/name: dirigera-exporter
    app.kubernetes.io/instance: dirigera-exporter
  ports:
    - name: http
      port: 9119
      targetPort: http
