apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graphite-exporter
  namespace: monitoring
  labels:
    app: graphite-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: graphite-exporter
  endpoints:
    - port: metrics
      interval: 30s
