apiVersion: ENC[AES256_GCM,data:H2c=,iv:VkhHIWjHBcJ7HbF3HJEyUdnom6+ISn012RLaK1xeDhg=,tag:eOqhf7cbDD5i+rEDC99qRw==,type:str]
kind: ENC[AES256_GCM,data:KLNhFoui,iv:GinHVTcdsVZcO6rs7XZ1knBssRA2JE9xuI0zqMOgSlo=,tag:dm+LDVsfykhQ9r0IAP9V9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NFiZNjiwTwOSU8SwSdesJI1Mb2d8Rw1v7luDMtzo+tuRreYD,iv:A3sn6cBYpGVUDprZoJSfQV43lbjsZ/M9M5kpvAob2eI=,tag:lCVvTsoXMAX08R0XjYyY3g==,type:str]
    namespace: ENC[AES256_GCM,data:0NE7b1i3buuLQpRQvSY=,iv:6ovh/ECh9JuYIpFUHd5ZB+jUCuEwm+YW+UfMhGXsYfQ=,tag:vu9Hgl/wHzDAfex6EKku0w==,type:str]
type: ENC[AES256_GCM,data:uGUDHHyN,iv:oDeukji59GpbhRc3XCr3q7EKm05xxrAJqlC59SW6frk=,tag:Dyiwdk8Vccc29O639N3Bgw==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:UMrXidE9DbogUEkStsO/RPT2R72a6922dYFlSaeTU5+pDEsSrfS4ayIPkdco3HdV+Mb7KfcWp6+eH5+9OtnJItFjRtG5RVjxoUCTJGITsnxDCOaTZTnVbvhuXCnTsCAjjGFSQcodbBmAVwhKxEm1sb+8QeA+dsxAOx1yuqoRJg9T42RQHm5ybbreDodDPSV7U2Nyd7ulY0LR6+Ztw36ohYKATYfdwGp1m/XUjgvfJFd37qQwgU24SROwRlxVvL0Xumkp7xsbNYgGX+xhXnIJqR2aEdGjxF9Hhlotjxgi5DGsCkDcqtjIrsRm7Jh5ZyO/DT4p6BoxsUdWd8qQ0vm3X2X2MC7hIv1yGWmuzVHDzT8+FCmIdRdESKy++eEGUGaUZKOD1qVqZF5S0C2UHJnmcFzsBuhqQNyR8wovqbe7lXnyO2d/S2eZdAvdPy1SlboBZXMmDw8oPmlijxPbC7AK56NX9b1yls7LVGQyQcfwmUP9pD5NzXo+lo8GiHnSwTW0HYwnRfYMS07M6tqcei24StF0pFR1/iJkmhjPayeE0RssCtPuCgSKG7eCkoQ2oQ3O+x6Z1LYMaLAQ0VnsJpMd63QUhGrsGONY1MbYGm7ZGJYLtY6zBYfkAXQ4JVIJimlFQUPk7zCtZL9gdQw57LWtmhzRxR5RX9Gtpdjgi2RxUOOC/kU+4VS1uEEZ0BPPcxcG25n3i69FiGlI4xrzrOCsotVkvqNyqpXHMt33QXtfSZBAy5MkZ1awR9ebabKCjgyGuElrjfI+qsAQNQm99b0dKcVGq1uhXkl8,iv:6rn+djw2+cswNNXPH3jB9G7rGlCNwV7z4cv2fXAmJfU=,tag:aOmEpc3w65IMMIgTogDNMw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTVFONm5RY2JSTTBzTCs4
            Mi8vRG9Eck9zWDNHSWFIQnBKb3pXNUZJb2tRCnQ4bDdxVnhvMHJlV1dpU3FMam4y
            Vm00eVpOQXNmbTU2eTB5LzVvblFTS2cKLS0tIHBDMEZYL0M3Smtrenk3U1FzYWRE
            VzQydXIrcm1kVlB3S0xlaWJWbGxDbUkKtCRSk/O5B1SARp/1bhY7LlUgpIqVsDzx
            wep9qRQENI/jEEU5FYA5+yBR4X1OC3/6wSVqdgCWjZ5LUPFJKt2M6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T23:04:19Z"
    mac: ENC[AES256_GCM,data:8MCdggSjrsNuO6KLAE+6X+0gd4K537RPA5w/L0Xs+gq5RhmcBxlP3xISvyW1Wa9XdVxHRVaL+1f9BSz9k3guYcsCcADwUXDpfKWMipVtVTf8IEcq04pi9+q6kiK9VHQ0ZX8DizzUB5g1guTZSPks6N20z8F72vzpzHnDXB+YX5M=,iv:aLLI2Ze6L4cwZMc3ODmpiax72gzXfN3LhLMXLMybLtw=,tag:yZaqxs3mR1kGWB6EzWi9nA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
