apiVersion: ENC[AES256_GCM,data:R2o=,iv:8nIQxxKDVpXUPOcH6XPvlsWYHm0Tg3YsAMAOcqDGO8c=,tag:bLcaiLKegIbR6kzTI26zrw==,type:str]
kind: ENC[AES256_GCM,data:RWJ0FJvr,iv:JVENE1useLKXOzZwZBiaXw3AEQW8o2g3Dn3LtA1KfLA=,tag:L6BCZ6CQbFQZceyeyU2Pyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GTu8tY7f27qfgImpYo6aEFVBgIB0/ek4PBuFDXSEy2Q=,iv:rUI6mgpBalArdRcDaMhi97rZ7OBkpozf0JHHCDOYjxg=,tag:GEk3nPB5627J6YNqafoUbw==,type:str]
    namespace: ENC[AES256_GCM,data:G7UpTkw8VLq49NXAd/c=,iv:M1kHCYjUwumh8NQ8q157gYldmYu9k7x6of3jMYfRf7Y=,tag:1XTcfZIWvC+JWIXqydw7Ug==,type:str]
type: ENC[AES256_GCM,data:+wqQbc4y,iv:NPCOCM3d190YS4kgpLYcMPIjhqal/wuKFDKzlB+lhvs=,tag:14MeJCRXHKTsq71JnzmNHQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:aws05ordb67nl0HRHO9qNBXo3yqtAmvtNO1nfHu1xKU5DUnxyrj87IkHU3SQiKc7OxbXpXSORR6FEZmDRdGPoqPkXnsviHPLNguCwFB/dqJ2i9B4iHa8qa/a9afQrVEEX3bBySN7s3wmA6Lqzvxyz4b7rkm8XxSRHJgXPL3H09CUA1jAuaQKlyfhRhFPQw0OWWCl60uabJRMrAJYPwapRgryxupgj8rr4eXnFzwrcDyHXB80folDXrofNZahUnSbB/Mudlj1mYZ+YIU26KyHog9sKE+kzLtsQz30qVFHColB9HK1H+BNZWGn/Zbl3tf/PWFhYAO8SL1l3eayvYj927T+VRL0z9NcDJo2jz8oYKGcUs/YqyVKthL/BBSzO3f4lPDrCQhzvPX42Lw87c9Y6o9Kvsp+DLmQGLrEBqMoqxirWEVqmPNnV+edVXslX8lH+qyTbNdfh7zvlc5DuVYvr5bXLMf0pcih8JLXCGNc7iua10v1CPiexOFuhPrZo3I+RraaGC0153fjNa4YVM+U73GD0OpTjQ4691CkZ9vg0v9PEPzvy6JQ+8h8QwuLUjl6UBQab9DoYPKmubc8LHs0AXnAmqj0EehXBWSPCvCIYG0EF1xY2VtYWxp2Ek2koAZFG3GNqVyXekGV3jUOauWiRUIPNWM2QVlI/XPIm5b8YkClAziyEGfC0jMrkk9NetctMr/bYHlauT9gHKhoq8pha2Mfb4tApl6CATGAA+14gsVct654ayEMK2Ct7/n0tOg1pJfsZ7i2UQrpdVse/iLamJ0sAvipociv,iv:PjXK5nf+0GJlNgpb58k6Wq7RVj+4TDENF3XhlWLUZyU=,tag:y+GVl1B036lNVH4R93sgkA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc1NPTzVPME1HNG82cTZW
            SjhVekZZSFFiYUwwT2grM3diaE9KMTB5YnhjCkRBV3JDajdLRTlRcm1wUEIrYUdR
            WGlUZklGQjRnTjVSVXdiQWhZazdmcmsKLS0tIElhS0h0TVBGaWZab2FSTERzVUtP
            MGduTUs5a0ZJMVRjTVdWb0hFVitjM0kK9QAWAPnYCJ3iwJ7XI9jRM5svFZ3huuzS
            D5fL5Z8TPhyUaHyLHthDVgp07uE2Qu3wEg0Rfm46RNocRf2R8Zcu5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T23:04:19Z"
    mac: ENC[AES256_GCM,data:AX2c5HSszTAwdpxyVxvO3VfHpL4hpTW4o1KVH/hRUTfdCem25LWgrmVBvc/J8G6GkPW3nCizRRys0kfhFR8a6NlDbu3LIA+1f44dgNluFSK8gReElQE25ADxdvR9jwciUNzNaUbqqXYHaTDiwMxV0bTk0xVdAgleanruvHx4RZ8=,iv:D049YqMhyRec7Yv1n6N3FsmbWbFVnozTaz+N1HYj7t4=,tag:oPcPIjki2qu5hQASD7rBqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
