apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-ssd
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-ssd
  resources:
    requests:
      storage: 5Gi
