apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - ingressroute-web.yaml
  - middleware-hsts.yaml
  - middleware-redirect-https.yaml
  - middleware-fail2ban-vaultwarden.yaml
  - pvc-data.yaml
  - pvc-data-old.yaml
generators:
  - secret-generator.yaml
