apiVersion: ENC[AES256_GCM,data:kCQ=,iv:3W9Mue9nNL6EUsnQu9ZMj2xb9JnLTVc13hk/I4Ze7EY=,tag:/rw+dC9k/Sb5umUkOF5nUQ==,type:str]
kind: ENC[AES256_GCM,data:9DVuuDhx,iv:i1rm0jkZTIwidDFFoRKwqxrfyHmKy3xELcBn+aYdJVc=,tag:z8SIlPHorBBwM6nvATxZaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xE6YlclNdjqUD93VpZYEoWbclQ==,iv:CccpvK/86+NTGaxP6O+1nKmt7dQowljGRSF5RubA9Ks=,tag:O1/2yIjEbfTBpVs/dHBmtw==,type:str]
    namespace: ENC[AES256_GCM,data:p/UTzHy60AiTFLw=,iv:Jph383TofV3yptm/ZzqWd0rxTIdpOttAYQlmcgvVxDU=,tag:mXx6J0k+Fg1RCa8dAvXN2Q==,type:str]
type: ENC[AES256_GCM,data:7lPwR1HA,iv:u4/IvadevIkveaFnaLCtXzHvadnHMwTCiLQsr4FdH4M=,tag:5pWdo4QskQiHbmANIId1zQ==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:BAsyMI6HINo+FjY+SzIADlgSMlDl43yQ13ouTCMWz0RMiAt/H7hkl+mHY4Vk77JYV7QeUz1R45FLO1Id48ExmQ==,iv:fKOpalZrHo+k1owN58/QC/I0gqVEN44AMfH+BSs5S/E=,tag:3hjgrRZ/+BU+Ah7GWHbVSw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:vxoxQia9fXBzKzvjrDm9g7ixXObNOoSIii40g4UKK87IkiuF,iv:UUUiiR7KDc/uEi9hLPzzJUkXEAdRLP5n4D78te36V/w=,tag:NIGoc3DCG+/An7YdIBVOOQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVER2dXNTY0tZblh2dkE2
            RERJSURsL3ZhN25KbFlLWGlRd3dkdUpxL1I0CmRDVmI4QWpzc1JaOERQTkxvQ3Y5
            SnBnYzR0Z1l3dlJBNW9MTkw2c3BjU1EKLS0tIFhsSm9yTkc2K0xuR1dTNkIzL2kr
            Q3UwRnJmVEliVHpodWJsQ25lQnEzSUkKBObfLV+k56aDpnGG9R3HDgnqC9WJqeG/
            4viA+bhlehutEt8CR4OGgqtuuC1c57gzoeieVE5jSv1eW7N67QsBHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T19:57:24Z"
    mac: ENC[AES256_GCM,data:O2G2DSKxDvxQXmFWOkxAK2Dlff+qrFH6Hm1bCc8wpw6WMu/N2yLuW3/mWO6epU+bGg0jtzK84DCtqrcEjB16ujxD4A9w2GeSnOkuspjPaaIY2HcL6gAIW3jCiw/ieB2I0Vg18VkT+5X/kn+lOBkfzIaR0T4am+hYZvkLI+tEITg=,iv:M47pRuZObDMrr4wo+z8vuTDFsjtiHh5bKRmaL+gyG68=,tag:1Z4vtsnnQa7lFuRQ9MIGDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
