apiVersion: ENC[AES256_GCM,data:XFY=,iv:VJU31gAxY/y8d6KzeJiySjufU7BBOO2Nt6Azu76a7DE=,tag:Sqd6QhsyE/Ox7jTexPb6HA==,type:str]
kind: ENC[AES256_GCM,data:+8rW15v3,iv:4y5cBE2gUuXa2dX6R8lqnR56ksJ5/8oKU0H13i/RYhc=,tag:lubEDgBlwiTPhaHn6cTWag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:edgkQmAnR2CrRuvpEnvIndSAdg==,iv:f6/7eVy/QyH54lD4doQz40AHPy3wLV1zcnXpolaKxKs=,tag:paD9oeOhZrTyMmo1YPWwNQ==,type:str]
    namespace: ENC[AES256_GCM,data:QgWl03Qd9jjoekc=,iv:rUvdcYFr4BkXGvmT8L4Qhsn+W5f6g2REuq0Fl4g1c9o=,tag:dnjjQR+LNNalqXeujsgU2Q==,type:str]
type: ENC[AES256_GCM,data:ev7ZC5AA,iv:88DI3tesPy1HD5ieFG1GAi//T8jQ25pOWj8+xP9C4OM=,tag:1a8ixGuWSJ4V2/e7ZAZ9yg==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:dp8xN5DzES8iSGV9Yv78UfqpNBgxUEEannrHMVs1ewbl0yz9fu9zX3q4sjfmb9FbQHelQFg6PfUPk6VWmSwIQ/RTtNWXz/hW7DKT3m9y8qoKoy33K+z+s1Y4YQKA3HQ2RQ==,iv:3qm7IYhcF1f7kDafPzTIX47v8swA8ThdJlCSJJNr0iw=,tag:IUX3qLXE13Fhsj5W+eos5g==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:NSp5oLo+CGsb1Xpa7uL6PfO0nHAC/b3pGjZ4/yuJPHDm+JeF,iv:uDMkYlDdUrlLE0jCyD7cWn2RSJxHfwsvJ/UYfZQaFfY=,tag:v+ZRGSUCKs8iQ9XrbO5pvw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdTVmYlpsWGI2MXhiamo2
            VlpiNWJtMWdNakpDM2ZGM3hCL085cnlBWVc0CjBLMWYrUUIrVjBjRjAxNlM5ZmhR
            Sm0rVFgyT3pEdCtMVkhVZEVLUFYxWkUKLS0tIFYyVmVnNGVtTFk3MHdPL2VobGxy
            LzRtLy9zWDZUbUd1ay9KY0pFbnBrU3MKdsrtIaRoDOzUBQANqfe/XV5CyKnHKYes
            hq0jF/K4puz83f1oIfqUtKOJ2dr5g/yaZr8Mqtp8j4A/eegsdU9jWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T13:11:16Z"
    mac: ENC[AES256_GCM,data:IQo6c4RTa7HlxIdlsL6W3POXVGBbjjFZoBPOiWI4pCVuspcFdcAsMj9lK3RBDjz3Vo6zfM9psCJ8l6chNxjuJdn3bSqt7/x4ne/iMPEbrgrc8zRPFzIQ57LK3VCXXaidsk+EZaTWlvq8Z+hdlM//EXZ4FWxAXPfzFSpMZipD3IQ=,iv:97FeXfnMhd9H2rFawDXlrrEHSAOjCi4kI1lHOuc535M=,tag:eRIOJVP1+ntel057iV6Q+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
