apiVersion: v1
kind: ConfigMap
metadata:
  name: security-txt
  namespace: traefik
data:
  security.txt: |
    -----BEGIN PGP SIGNED MESSAGE-----
    Hash: SHA256

    Contact: mailto:yornik@yornik.nl
    Encryption: https://fedishark.eu/.well-known/pgp-key.txt
    Expires: 2027-02-19T00:00:00.000Z
    Preferred-Languages: en, nl
    Canonical: https://fedishark.eu/.well-known/security.txt
    Canonical: https://yornik.eu/.well-known/security.txt
    Canonical: https://pub.fedishark.eu/.well-known/security.txt
    Canonical: https://jelly.yornik.eu/.well-known/security.txt
    Canonical: https://secrets.yornik.eu/.well-known/security.txt
    Canonical: https://grafana.fedishark.eu/.well-known/security.txt
    Canonical: https://passwords.yornik.eu/.well-known/security.txt
    Canonical: https://todo.yornik.eu/.well-known/security.txt
    Canonical: https://asf.fedishark.eu/.well-known/security.txt
    Canonical: https://qbittorrent.fedishark.eu/.well-known/security.txt
    Canonical: https://omni.fedishark.eu/.well-known/security.txt
    Canonical: https://argocd.fedishark.eu/.well-known/security.txt
    -----BEGIN PGP SIGNATURE-----

    iHUEARYIAB0WIQQwRaQ5G6gwBtDu5Aft+zCFSkKz8AUCaa1ccwAKCRDt+zCFSkKz
    8I3BAQCDCKnNlp+MOcdDFeIh/KDYNQEqzdETn5U0ftZYZ91kJAD+KlytzEodud7N
    le7AHD4nL/bMdG2d5PgriCwh6R9vKQI=
    =CqmF
    -----END PGP SIGNATURE-----
  pgp-key.txt: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEaZd5AxYJKwYBBAHaRw8BAQdA+F5FrdhHQYLTZJxmqTH5cUP+x0rkmEjZi4Em
    ovZf21a0JUZlZGlTaGFyayBTZWN1cml0eSA8eW9ybmlrQHlvcm5pay5ubD6IlgQT
    FggAPhYhBDBFpDkbqDAG0O7kB+37MIVKQrPwBQJpl3kDAhsDBQkB4TOABQsJCAcC
    BhUKCQgLAgQWAgMBAh4BAheAAAoJEO37MIVKQrPwZnYBALJatQ8zxDPPaD7EZuKH
    8PCmi/9agbqEvVM1joL9Nm/gAP9dxrg5bnWZqf8viggtKNff070PhEFBg9GJXCAA
    HsZlAg==
    =0uRZ
    -----END PGP PUBLIC KEY BLOCK-----
