apiVersion: ENC[AES256_GCM,data:XU8=,iv:9TTQSGRd2CAuW37nE1qe+nw0umAuyzIcmL2NZPYzmgg=,tag:ofQCnsCe/jwFpXQERauCng==,type:str]
kind: ENC[AES256_GCM,data:I86mDQOx,iv:rjPRcf/KMGBlkD1+b2LnQuwyKTW5ndYMFrpD2kEbiKQ=,tag:Z7yNs6G6QclmBZaGMoZKJg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eZDG5/eNa6VfHcdQDwjQb7JwoKjbgQ==,iv:Ywq0TNYaB3fS8EcShmRu4sAPBLRm7G8LPm0Rw2F7Zh4=,tag:fuYvfJpRSOQ513bKO4grAw==,type:str]
    namespace: ENC[AES256_GCM,data:rp7wrvtcdEeEZoWA,iv:k5IUK9r2+AzHytqhWPUlCs6Mugc2LISl9mJ0pqCkuQ0=,tag:Dl+RUop+l2cW6oVnTMvOnQ==,type:str]
type: ENC[AES256_GCM,data:nxKrp/he,iv:Y68P+dQ+/aZdgvNyYl3G7OTIYROSGCDQAui5jc9q/JU=,tag:pRceGVotZOGZNFPq5Ec6qQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:fv/XZNoR9TZBHfBwD5/W8m+JJCjXgDZnkqDukq81dyrP7JfImR9Few==,iv:jK3joh/h2R3xf9cUjlbS3ovARxTEHBLquvW5GO35e/w=,tag:X6572J3BLVJhORjbOfFofA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OTJ1QTR6MlYxNVpHd2Fl
            ejF2SHIwRjdnNjJSc1U0TzNzNUw5NE5Cb3hzClc3R0xQVm91TFdkSENVSEgzUkEv
            czF5Ukg3QTJCSEVyUndISjlPcVl3VWMKLS0tIElOVVNWdFlDUUJyUEI3ZjFGSjBG
            elFNNCtKTHhKQm5OdUxoa0tjRjU0TjQK1dSfWt5cwgsUbXZqGLgzCfLCnuPK1sDy
            S1XDBlJ4csDOqM+OhYQ5bsczi3pbF5eDtYnjHrtuhJ4Atxi2tyN5NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T12:18:28Z"
    mac: ENC[AES256_GCM,data:AcV7dNH6Eqx2fdkiLCEvhqv2pZrfKbNEknDlHmirekKos3J0pD2zuFkdEjGrpTPxVp6+SpXI8hDuPxDJQNQv/rWyXXoCM/WnLxiVZ/OwepivDRiYLJCaQG70j64HQFexioaXwqX+Le9dgvTzXGlDA5yzzOtCKAiL+Njh23SCt1c=,iv:JpOkPQm24P1DsxsEglN6/bf7GSMfA4EWed0FZnyoTW4=,tag:yU3L5ZS2cfNMjw8d7zDgrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
